name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install and Build
      run: yarn && yarn build

    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:vue
    - name: Push the Docker image
      run: docker push registry.cn-beijing.aliyuncs.com/dreamhunter/awsl:vue
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: registry.cn-beijing.aliyuncs.com
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - name: Rename VUE_APP_BASE_API
      run: echo "VUE_APP_BASE_API=http://awsl-py.dev.jcstaff.club" > .env.production
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag dreamhunter2333.azurecr.io/awsl/awsl-front:v1
    - name: Push the Docker image
      run: docker push dreamhunter2333.azurecr.io/awsl/awsl-front:v1
  
